name: Push on fork

on: [fork]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.PUSH_API_KEY }}
        MESSAGE: "Someone just forked TypeTypeGo!"
